name: Best Cars CI/CD

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-python:
    name: Lint Python Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Print working directory
        run: pwd
      - name: Install dependencies
        run: pip install -r server/requirements.txt flake8
      - name: Run Linter
        run: flake8 server/djangoapp server/djangoproj --exclude=server/djangoapp/migrations --ignore=E501,W503 --exit-zero

  lint-javascript:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install JSHint
        run: npm install --global jshint
      - name: Run Linter
        run: jshint server/frontend/src --exclude-path server/frontend/node_modules || true
